daily/0421/workshop/crud/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
]

daily/0421/workshop/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

daily/0421/workshop/crud/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

daily/0421/workshop/crud/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

daily/0421/workshop/crud/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

daily/0421/workshop/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
	<h2>DETAIL</h2>
	<hr>
	<h3>{{ article.pk }}번글</h3>
	<p>제목: {{ article.title }}</p>
	<p>내용: {{ article.content }}</p>
	<p>생성 시각: {{ article.created_at }}</p>
	<p>수정 시각: {{ article.updated_at }}</p>
	<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

daily/0421/workshop/crud/articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
	<h2>CREATE</h2>
	<hr>
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button>Submit</button>
	</form>
	<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

daily/0421/workshop/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
	<h2>INDEX</h2>
	<a href="{% url 'articles:create' %}">CREATE</a>
	<hr>
	{% for article in articles %}
		<h3>
			<ul>
				<li>{{ article.pk }}</li>
				<li><a href="{% url 'articles:detail' article.pk%}">{{ article.title }}</a></li>
			</ul>
		</h3>
	{% endfor %}
{% endblock %}

daily/0421/workshop/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>workshop</title>
</head>
<body>
	<h1>Articles</h1>
	<hr>
	{% block content %}
	{% endblock %}
</body>
</html>